/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/user/onboarding': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 온보딩 설문 제출
     * @description 사용자의 초기 설문 데이터(닉네임, 성별, 직업, 관심사, PHQ-9, PSS-10, MBI 점수 등)를 제출합니다. UserProfile이 없으면 자동 생성됩니다.
     */
    post: operations['submitOnboarding'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/user/auth/reissue': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 토큰 재발급
     * @description Refresh Token으로 새로운 Access Token과 Refresh Token을 발급받습니다.
     */
    post: operations['reissue'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/user/auth/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 일반 회원가입
     * @description 이메일/비밀번호로 일반 사용자 계정을 생성합니다. (소셜 로그인이 아닌 경우)
     */
    post: operations['register'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/user/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 일반 로그인
     * @description 이메일/비밀번호로 로그인하여 Access Token과 Refresh Token을 발급받습니다.
     */
    post: operations['login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/reports/analyze': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 감정 분석 생성
     * @description 사용자의 최근 활동 데이터를 기반으로 감정 분석 리포트를 생성합니다.
     */
    post: operations['createAnalysis'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/missions/{missionId}/complete': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 미션 완료 처리
     * @description 특정 미션을 완료 처리하고, 포인트 및 스트릭 보너스를 계산하여 반환합니다.
     */
    post: operations['completeMission'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/counselors/inquiries': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 상담사 등록 문의 제출
     * @description 로그인 없이 상담사 등록 요청을 접수합니다. 동일 이메일의 PENDING 문의가 있으면 409 오류가 발생하며, 접수 완료 시 영업일 기준 2~3일 내 개별 연락을 드립니다.
     */
    post: operations['submitInquiry'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/counselors/inquiries/admin/{id}/reject': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 상담사 문의 거절
     * @description 자격 미달 또는 검증 실패 시 거절 처리합니다.
     */
    post: operations['rejectInquiry'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/counselors/inquiries/admin/{id}/approve': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 상담사 문의 승인
     * @description nbcc.org/verify 등에서 자격 확인 후 승인을 처리합니다.
     */
    post: operations['approveInquiry'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/counselor/test/accounts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 전체 상담사 목록 조회
     * @description 등록된 모든 상담사의 로그인 정보를 조회합니다. 비밀번호는 암호화되어 있어 반환되지 않습니다.
     */
    get: operations['getAllCounselors'];
    put?: never;
    /**
     * 테스트 상담사 계정 생성
     * @description 테스트용 상담사 계정을 생성합니다. User(COUNSELOR) + Counselor 엔티티가 함께 생성되며 즉시 ACTIVE 상태로 설정됩니다.
     */
    post: operations['createTestCounselor'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/counselor/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Access Token 갱신
     * @description Refresh Token 쿠키를 이용해 Access Token을 재발급합니다.
     */
    post: operations['refresh'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/counselor/auth/password-reset': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 비밀번호 재설정 링크 발송
     * @description 상담사 이메일을 검증하고 24시간 유효한 비밀번호 재설정 링크를 발송합니다.
     */
    post: operations['requestPasswordReset'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/counselor/auth/password-reset/confirm': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 비밀번호 재설정 완료
     * @description 메일로 수신한 토큰과 새 비밀번호를 전달하면 상담사 계정의 비밀번호를 갱신합니다.
     */
    post: operations['confirmPasswordReset'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/counselor/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 로그아웃
     * @description Refresh Token을 폐기하고 쿠키를 만료시킵니다.
     */
    post: operations['logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/counselor/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 상담사 로그인
     * @description 상담사 계정 정보를 검증한 뒤 2차 인증(OTP)을 위한 challengeId를 발급합니다.
     */
    post: operations['login_1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/counselor/auth/2fa/verify': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * OTP 검증 및 토큰 발급
     * @description challengeId + OTP 코드로 검증 후 Access/Refresh Token을 발급합니다.
     */
    post: operations['verifyOtp'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/counselor/auth/2fa/resend': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * OTP 재전송
     * @description 기존 challengeId로 새로운 OTP를 발급합니다.
     */
    post: operations['resendOtp'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 전체 사용자 목록 조회
     * @description 등록된 모든 사용자의 프로필 정보를 조회합니다. (관리자용)
     */
    get: operations['getAllUsers'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/users/{userId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 특정 사용자 조회
     * @description userId로 특정 사용자의 프로필 정보를 조회합니다.
     */
    get: operations['getUser'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/users/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 내 정보 조회
     * @description JWT 토큰 기반으로 로그인한 사용자의 프로필 정보를 조회합니다.
     */
    get: operations['getMyInfo'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/user/onboarding/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 전체 온보딩 데이터 조회
     * @description 모든 사용자의 온보딩 데이터를 조회합니다. (상담사/관리자용)
     */
    get: operations['getAllOnboarding'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/user/onboarding/users/{userId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 특정 사용자 온보딩 조회
     * @description userId로 특정 사용자의 온보딩 데이터를 조회합니다.
     */
    get: operations['getOnboarding'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/user/onboarding/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 내 온보딩 데이터 조회
     * @description 로그인한 사용자의 온보딩 설문 결과 및 분석(심각도, 피드백)을 반환합니다.
     */
    get: operations['getMyOnboarding'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/reports': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 내 감정 리포트 목록 조회
     * @description 로그인한 사용자의 감정 분석 리포트 목록을 조회합니다.
     */
    get: operations['getMyReports'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/reports/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 감정 리포트 상세 조회
     * @description 리포트 ID로 특정 감정 분석 리포트의 상세 내용을 조회합니다.
     */
    get: operations['getReport'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/records': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 내 활동 기록 조회
     * @description 로그인한 사용자의 활동 기록을 페이지네이션으로 조회합니다. 기본 페이지 사이즈는 20입니다.
     */
    get: operations['getRecords'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/missions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 오늘의 미션 조회
     * @description 로그인한 사용자의 오늘의 추천 미션, 진행률, 최근 완료 히스토리를 반환합니다. 오늘의 미션이 없으면 자동 생성됩니다.
     */
    get: operations['getMissions'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/counselors/inquiries/admin': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 상담사 문의 목록 조회
     * @description 상태별 상담사 등록 문의를 페이지네이션으로 조회합니다.
     */
    get: operations['getInquiries'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/counselors/inquiries/admin/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 상담사 문의 상세 조회
     * @description 단일 상담사 등록 문의의 상세 정보를 조회합니다.
     */
    get: operations['getInquiry'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 헬스체크
     * @description 서버가 정상 동작 중인지 확인합니다.
     */
    get: operations['healthCheck'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ErrorResponse: {
      /** @example RESOURCE_NOT_FOUND */
      code?: string;
      /** @example 요청한 리소스를 찾을 수 없습니다 */
      message?: string;
      data?: Record<string, never> | null;
    };
    OnboardingRequest: {
      concerns?: string[];
      /** Format: int32 */
      phq9Score?: number;
      phq9Answers?: number[];
      /** Format: int32 */
      pss10Score?: number;
      pss10Answers?: number[];
      /** Format: int32 */
      mbiScore?: number;
      /** Format: int32 */
      mbiScoreBurnout?: number;
      /** Format: int32 */
      mbiScoreDepersonalisation?: number;
      /** Format: int32 */
      mbiScorePersonalAchievement?: number;
      mbiAnswers?: number[];
      nickname?: string;
      gender?: string;
      occupation?: string;
      birthDate?: string;
      /** Format: int32 */
      age?: number;
    };
    ApiResponseVoid: {
      code?: string;
      message?: string;
      data?: Record<string, never>;
    };
    /** @description 토큰 재발급 요청 */
    ReissueRequest: {
      /**
       * @description Refresh Token
       * @example eyJhbGciOiJIUzI1NiJ9...
       */
      refreshToken?: string;
    };
    /** @description 회원가입 요청 */
    RegisterRequest: {
      /**
       * @description 이메일
       * @example user@example.com
       */
      email?: string;
      /**
       * @description 비밀번호
       * @example password123
       */
      password?: string;
      /**
       * @description 이름
       * @example 홍길동
       */
      name?: string;
    };
    /** @description 상담사 로그인 요청 */
    LoginRequest: {
      /**
       * @description 상담사로 등록된 회사 이메일
       * @example hyunho.jang.biz@gmail.com
       */
      email: string;
      /**
       * @description 8~14자의 비밀번호
       * @example S3curePass!
       */
      password: string;
    };
    ApiResponseEmotionReportResponse: {
      code?: string;
      message?: string;
      data?: components['schemas']['EmotionReportResponse'];
    };
    EmotionReportResponse: {
      /** Format: int64 */
      id?: number;
      /** Format: date-time */
      sessionDate?: string;
      /** Format: double */
      sentimentScore?: number;
      primaryEmotion?: string;
      summary?: string;
      keywords?: string[];
      /** Format: date-time */
      createdAt?: string;
    };
    /** @description 미션 완료 요청 — 완료 전후 기분 점수 및 코멘트 */
    MissionCompletionRequest: {
      /**
       * Format: int32
       * @description 미션 수행 전 기분 점수 (1~5)
       * @example 2
       */
      moodBefore?: number;
      /**
       * Format: int32
       * @description 미션 수행 후 기분 점수 (1~5)
       * @example 4
       */
      moodAfter?: number;
      /**
       * @description 미션 완료 후 소감
       * @example 산책하니 기분이 한결 나아졌어요
       */
      comment?: string;
    };
    ApiResponseMissionCompletionResponse: {
      code?: string;
      message?: string;
      data?: components['schemas']['MissionCompletionResponse'];
    };
    /** @description 미션 완료 응답 — 획득 포인트 및 스트릭 보너스 */
    MissionCompletionResponse: {
      /**
       * Format: int32
       * @description 이번에 획득한 포인트
       * @example 40
       */
      pointsEarned?: number;
      /**
       * Format: int32
       * @description 스트릭 보너스 포인트
       * @example 10
       */
      streakBonus?: number;
      /**
       * Format: int32
       * @description 누적 총 포인트
       * @example 350
       */
      totalPoints?: number;
      /**
       * @description 완료 메시지
       * @example 잘했어요! 오늘도 한 걸음 나아갔어요.
       */
      message?: string;
    };
    /** @description 상담사 등록 문의 요청 */
    InquirySubmitRequest: {
      /**
       * @description 상담사 이름
       * @example 김상담
       */
      name: string;
      /**
       * @description 연락받을 이메일
       * @example counselor@example.com
       */
      email?: string;
      /**
       * @description 연락처
       * @example 010-1234-5678
       */
      phone?: string;
      /**
       * @description 소속 기관명
       * @example 서울상담센터
       */
      organization?: string;
      /**
       * @description 라이선스 번호
       * @example A1234567
       */
      licenseNumber?: string;
      /**
       * @description 추가 문의사항
       * @example 오전 시간대 연락 가능합니다
       */
      message?: string;
    };
    /** @description 상담사 등록 문의 응답 */
    InquirySubmitResponse: {
      /**
       * Format: int64
       * @description 문의 ID
       * @example 1
       */
      inquiryId?: number;
      /**
       * @description 문의자 이름
       * @example 김상담
       */
      name?: string;
      /**
       * Format: date-time
       * @description 문의 등록 시간
       */
      submittedAt?: string;
      /**
       * @description 예상 응답 시간 안내
       * @example 영업일 기준 2~3일 내 연락드리겠습니다
       */
      expectedResponseMessage?: string;
    };
    /** @description 상담사 등록 문의 처리 요청 */
    InquiryProcessRequest: {
      /**
       * @description 관리자 메모
       * @example 자격증 검증 완료
       */
      adminNote?: string;
    };
    /** @description 상담사 등록 문의 상세 응답 */
    InquiryDetailResponse: {
      /**
       * Format: int64
       * @description 문의 ID
       * @example 12
       */
      id?: number;
      /**
       * @description 이름
       * @example 김상담
       */
      name?: string;
      /**
       * @description 이메일
       * @example counselor@example.com
       */
      email?: string;
      /**
       * @description 연락처
       * @example 010-1234-5678
       */
      phone?: string;
      /**
       * @description 소속
       * @example 서울상담센터
       */
      organization?: string;
      /**
       * @description 라이선스 번호
       * @example A1234567
       */
      licenseNumber?: string;
      /** @description 문의 메시지 */
      message?: string;
      /**
       * @description 처리 상태
       * @example PENDING
       * @enum {string}
       */
      status?: 'PENDING' | 'APPROVED' | 'REJECTED';
      /** @description 관리자 메모 */
      adminNote?: string;
      /**
       * Format: date-time
       * @description 문의 생성일시
       */
      createdAt?: string;
      /**
       * Format: date-time
       * @description 처리 완료 일시
       */
      processedAt?: string;
    };
    /** @description 테스트 상담사 계정 생성 요청 */
    CreateTestCounselorRequest: {
      /**
       * @description 이메일
       * @example test-counselor@kkebi.com
       */
      email: string;
      /**
       * @description 비밀번호
       * @example password123
       */
      password: string;
      /**
       * @description 이름
       * @example 테스트 상담사
       */
      name: string;
    };
    ApiResponse: {
      code?: string;
      message?: string;
      data?: Record<string, never>;
    };
    PasswordResetRequest: {
      email: string;
    };
    PasswordResetConfirmRequest: {
      token: string;
      newPassword: string;
      confirmPassword: string;
    };
    /** @description OTP 검증 요청 */
    OtpVerifyRequest: {
      /**
       * @description 로그인 단계에서 발급된 챌린지 ID
       * @example c9f1cb16-867f-47d1-b3f0-5d85b81d7a9d
       */
      challengeId: string;
      /**
       * @description 이메일로 받은 6자리 OTP 코드
       * @example 123456
       */
      otpCode: string;
    };
    /** @description OTP 재전송 요청 */
    OtpResendRequest: {
      /**
       * @description 재전송할 챌린지 ID
       * @example c9f1cb16-867f-47d1-b3f0-5d85b81d7a9d
       */
      challengeId: string;
    };
    ApiResponseListUserResponse: {
      code?: string;
      message?: string;
      data?: components['schemas']['UserResponse'][];
    };
    UserResponse: {
      /** Format: int64 */
      userId?: number;
      email?: string;
      name?: string;
      provider?: string;
      nickname?: string;
      gender?: string;
      occupation?: string;
      birthDate?: string;
      /** Format: int32 */
      age?: number;
      phoneNumber?: string;
      preferences?: {
        [key: string]: Record<string, never>;
      };
      concerns?: string[];
      /** Format: int32 */
      level?: number;
      /** Format: int32 */
      xp?: number;
      /** Format: int32 */
      points?: number;
      /** Format: int32 */
      streak?: number;
    };
    ApiResponseUserResponse: {
      code?: string;
      message?: string;
      data?: components['schemas']['UserResponse'];
    };
    ApiResponseListOnboardingResponse: {
      code?: string;
      message?: string;
      data?: components['schemas']['OnboardingResponse'][];
    };
    AssessmentResult: {
      /** Format: int32 */
      score?: number;
      level?: string;
      feedback?: string;
    };
    MbiDetails: {
      /** Format: int32 */
      burnout?: number;
      /** Format: int32 */
      depersonalisation?: number;
      /** Format: int32 */
      personalAchievement?: number;
    };
    MbiResult: {
      /** Format: int32 */
      score?: number;
      level?: string;
      feedback?: string;
      details?: components['schemas']['MbiDetails'];
    };
    OnboardingResponse: {
      /** Format: int64 */
      userId?: number;
      nickname?: string;
      gender?: string;
      occupation?: string;
      birthDate?: string;
      /** Format: int32 */
      age?: number;
      preferences?: {
        [key: string]: Record<string, never>;
      };
      concerns?: string[];
      phq9?: components['schemas']['AssessmentResult'];
      pss10?: components['schemas']['AssessmentResult'];
      mbi?: components['schemas']['MbiResult'];
    };
    ApiResponseOnboardingResponse: {
      code?: string;
      message?: string;
      data?: components['schemas']['OnboardingResponse'];
    };
    ApiResponseListEmotionReportResponse: {
      code?: string;
      message?: string;
      data?: components['schemas']['EmotionReportResponse'][];
    };
    Pageable: {
      /** Format: int32 */
      page?: number;
      /** Format: int32 */
      size?: number;
      sort?: string[];
    };
    ApiResponsePageRecordDto: {
      code?: string;
      message?: string;
      data?: components['schemas']['PageRecordDto'];
    };
    PageRecordDto: {
      /** Format: int32 */
      totalPages?: number;
      /** Format: int64 */
      totalElements?: number;
      first?: boolean;
      last?: boolean;
      pageable?: components['schemas']['PageableObject'];
      /** Format: int32 */
      numberOfElements?: number;
      /** Format: int32 */
      size?: number;
      content?: components['schemas']['RecordDto'][];
      /** Format: int32 */
      number?: number;
      sort?: components['schemas']['SortObject'];
      empty?: boolean;
    };
    PageableObject: {
      /** Format: int32 */
      pageSize?: number;
      /** Format: int32 */
      pageNumber?: number;
      paged?: boolean;
      unpaged?: boolean;
      /** Format: int64 */
      offset?: number;
      sort?: components['schemas']['SortObject'];
    };
    RecordDto: {
      id?: string;
      /** Format: date-time */
      date?: string;
      type?: string;
      title?: string;
      /** Format: int32 */
      score?: number;
      mood?: string;
      notes?: string;
    };
    SortObject: {
      sorted?: boolean;
      unsorted?: boolean;
      empty?: boolean;
    };
    ApiResponseMissionResponse: {
      code?: string;
      message?: string;
      data?: components['schemas']['MissionResponse'];
    };
    MissionDto: {
      /** Format: int64 */
      id?: number;
      category?: string;
      title?: string;
      difficulty?: string;
      duration?: string;
      /** Format: int32 */
      points?: number;
      completed?: boolean;
    };
    MissionHistoryDto: {
      /** Format: int64 */
      id?: number;
      title?: string;
      /** Format: date-time */
      completedAt?: string;
      /** Format: int32 */
      pointsEarned?: number;
    };
    MissionProgress: {
      /** Format: int32 */
      completed?: number;
      /** Format: int32 */
      total?: number;
      /** Format: int32 */
      streak?: number;
    };
    MissionResponse: {
      progress?: components['schemas']['MissionProgress'];
      recommended?: components['schemas']['MissionDto'][];
      history?: components['schemas']['MissionHistoryDto'][];
    };
    ApiResponseString: {
      code?: string;
      message?: string;
      data?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  submitOnboarding: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['OnboardingRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseVoid'];
        };
      };
    };
  };
  reissue: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ReissueRequest'];
      };
    };
    responses: {
      /** @description 토큰 재발급 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "code": "SUCCESS",
           *       "message": "요청이 성공적으로 처리되었습니다",
           *       "data": {
           *         "accessToken": "eyJhbGciOiJIUzI1NiJ9...",
           *         "refreshToken": "eyJhbGciOiJIUzI1NiJ9..."
           *       }
           *     }
           */
          'application/json': unknown;
        };
      };
    };
  };
  register: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterRequest'];
      };
    };
    responses: {
      /** @description 회원가입 성공 — 생성된 userId 반환 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "code": "SUCCESS",
           *       "message": "요청이 성공적으로 처리되었습니다",
           *       "data": 1
           *     }
           */
          'application/json': unknown;
        };
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest'];
      };
    };
    responses: {
      /** @description 로그인 성공 — JWT 토큰 발급 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "code": "SUCCESS",
           *       "message": "요청이 성공적으로 처리되었습니다",
           *       "data": {
           *         "accessToken": "eyJhbGciOiJIUzI1NiJ9...",
           *         "refreshToken": "eyJhbGciOiJIUzI1NiJ9..."
           *       }
           *     }
           */
          'application/json': unknown;
        };
      };
    };
  };
  createAnalysis: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseEmotionReportResponse'];
        };
      };
    };
  };
  completeMission: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description 완료할 미션 ID
         * @example 1
         */
        missionId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['MissionCompletionRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseMissionCompletionResponse'];
        };
      };
    };
  };
  submitInquiry: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description 접수에 필요한 기본 정보 */
    requestBody: {
      content: {
        'application/json': components['schemas']['InquirySubmitRequest'];
      };
    };
    responses: {
      /** @description 문의 접수 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['InquirySubmitResponse'];
        };
      };
      /** @description 입력값 검증 실패 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description 동일 이메일 PENDING 문의 존재 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  rejectInquiry: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    /** @description 거절 사유 메모 */
    requestBody: {
      content: {
        'application/json': components['schemas']['InquiryProcessRequest'];
      };
    };
    responses: {
      /** @description 거절 완료 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['InquiryDetailResponse'];
        };
      };
      /** @description 이메일 미등록 등으로 거절 불가 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description 인증 실패 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description ADMIN 권한 없음 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description 문의 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description 이미 처리된 문의 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description 메일 발송 실패 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  approveInquiry: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    /** @description 승인 시 남길 관리자 메모 */
    requestBody: {
      content: {
        'application/json': components['schemas']['InquiryProcessRequest'];
      };
    };
    responses: {
      /** @description 승인 완료 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['InquiryDetailResponse'];
        };
      };
      /** @description 이메일 미등록 등으로 승인 불가 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description 인증 실패 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description ADMIN 권한 없음 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description 문의 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description 이미 처리된 문의 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description 메일 발송 실패 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  getAllCounselors: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 상담사 목록 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "code": "SUCCESS",
           *       "message": "요청이 성공적으로 처리되었습니다",
           *       "data": [
           *         {
           *           "userId": 1,
           *           "counselorId": 1,
           *           "email": "test-counselor@kkebi.com",
           *           "name": "테스트 상담사",
           *           "status": "ACTIVE"
           *         }
           *       ]
           *     }
           */
          'application/json': unknown;
        };
      };
    };
  };
  createTestCounselor: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateTestCounselorRequest'];
      };
    };
    responses: {
      /** @description 상담사 계정 생성 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "code": "SUCCESS",
           *       "message": "요청이 성공적으로 처리되었습니다",
           *       "data": {
           *         "userId": 1,
           *         "counselorId": 1,
           *         "email": "test-counselor@kkebi.com",
           *         "name": "테스트 상담사",
           *         "status": "ACTIVE"
           *       }
           *     }
           */
          'application/json': unknown;
        };
      };
    };
  };
  refresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie: {
        /** @description HttpOnly 쿠키에 저장된 Refresh Token */
        refreshToken: string;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Access Token 갱신 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiResponse'];
        };
      };
      /** @description Refresh Token 누락 또는 만료 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description 재사용이 감지된 Refresh Token */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  requestPasswordReset: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PasswordResetRequest'];
      };
    };
    responses: {
      /** @description 재설정 메일 발송 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiResponse'];
        };
      };
      /** @description 등록되지 않은 상담사 이메일 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  confirmPasswordReset: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PasswordResetConfirmRequest'];
      };
    };
    responses: {
      /** @description 비밀번호 재설정 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiResponse'];
        };
      };
      /** @description 유효하지 않은/만료된 토큰 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie: {
        /** @description HttpOnly 쿠키에 저장된 Refresh Token */
        refreshToken: string;
      };
    };
    requestBody?: never;
    responses: {
      /** @description 로그아웃 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiResponse'];
        };
      };
      /** @description Refresh Token 누락 또는 만료 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  login_1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description 로그인할 상담사의 이메일과 비밀번호 */
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest'];
      };
    };
    responses: {
      /** @description 2FA challenge 생성 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiResponse'];
        };
      };
      /** @description 이메일 또는 비밀번호 불일치 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description 상담사 권한이 아닌 계정 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  verifyOtp: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description challengeId와 이메일로 수신한 6자리 OTP 코드 */
    requestBody: {
      content: {
        'application/json': components['schemas']['OtpVerifyRequest'];
      };
    };
    responses: {
      /** @description OTP 검증 성공, Access Token 발급 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiResponse'];
        };
      };
      /** @description 잘못된 OTP */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description OTP 시도 횟수 초과 */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  resendOtp: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description 유효기간 내 challengeId */
    requestBody: {
      content: {
        'application/json': components['schemas']['OtpResendRequest'];
      };
    };
    responses: {
      /** @description OTP 재전송 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiResponse'];
        };
      };
      /** @description 만료된 challengeId */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  getAllUsers: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseListUserResponse'];
        };
      };
    };
  };
  getUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description 조회할 사용자 ID
         * @example 1
         */
        userId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseUserResponse'];
        };
      };
    };
  };
  getMyInfo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseUserResponse'];
        };
      };
    };
  };
  getAllOnboarding: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseListOnboardingResponse'];
        };
      };
    };
  };
  getOnboarding: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description 조회할 사용자 ID
         * @example 1
         */
        userId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseOnboardingResponse'];
        };
      };
    };
  };
  getMyOnboarding: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseOnboardingResponse'];
        };
      };
    };
  };
  getMyReports: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseListEmotionReportResponse'];
        };
      };
    };
  };
  getReport: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description 리포트 ID
         * @example 1
         */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseEmotionReportResponse'];
        };
      };
    };
  };
  getRecords: {
    parameters: {
      query: {
        /**
         * @description 페이지 번호 (0부터 시작)
         * @example 0
         */
        pageable: components['schemas']['Pageable'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponsePageRecordDto'];
        };
      };
    };
  };
  getMissions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseMissionResponse'];
        };
      };
    };
  };
  getInquiries: {
    parameters: {
      query?: {
        /** @description 필터링할 처리 상태 (미지정 시 전체 조회) */
        status?: 'PENDING' | 'APPROVED' | 'REJECTED';
        /** @description Zero-based page index (0..N) */
        page?: number;
        /** @description The size of the page to be returned */
        size?: number;
        /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
        sort?: string[];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['InquiryDetailResponse'];
        };
      };
      /** @description 인증 실패 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description ADMIN 권한 없음 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  getInquiry: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['InquiryDetailResponse'];
        };
      };
      /** @description 인증 실패 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description ADMIN 권한 없음 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description 문의 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  healthCheck: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseString'];
        };
      };
    };
  };
}
